variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
# PREFIX: /usr/
  DOCKER_FILE: utils/Dockerfile
  DOCKER_TAG: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: cricket
  # MAKE_OPTS: -j 16

before_script:
  - git config --local core.longpaths true
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - prepare
  - build
  - test

# For some reason, GitLab CI prunes the contents of the submodules so we need to restore them.
before_script:
#   - git submodule foreach git checkout .

# Stage: prepare
##############################################################################

# Build docker image
prepare:centos7:docker-dev:
  stage: prepare
  script:
    - docker build
        --file ${DOCKER_FILE}
        --tag ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
        --tag ${DOCKER_IMAGE_DEV}:latest .
  tags:
    - shell
    - linux

# check if styleguide is fulfilled
#style_check:
#  stage: build
#  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
#  allow_failure: true
#  tags:
#    - docker
#  script:
#    - ls
#    - utils/test_style.sh

# Stage: build
##############################################################################

build:
  stage: build
  script:
   - make -j 32
  artifacts:
    expire_in: 1 week
    paths:
      - cpu/cricket-client.so
      - cpu/cricket-server.so
      - gpu/cricket
      - submodules/libtirpc/install/lib/libtirpc.so*
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
  cache:
    paths:
      - gpu/build
      - cpu/*.o
      - tests/*.o
      - submodules/libtirpc/install
    key: build
  tags:
    - docker


test:
  stage: test
  script:
    - scp cpu/cricket-server.so ghost:~/artifacts/
    - scp submodules/libtirpc/install/lib/libtirpc.so* ghost:~/artifacts/
    - scp tests/test_kernel ghost:~/artifacts/
    - ssh ghost "LD_PRELOAD=/local-home/gitlab-runner/artifacts/libtirpc.so.3:/local-home/gitlab-runner/artifacts/cricket-server.so /local-home/gitlab-runner/artifacts/test_kernel" &
    - LD_PRELOAD=/cricket/submodule/libtirpc/install/lib/libtirpc.so.3:/cricket/cpu/cricket-client.so /cricket/tests/test_kernel
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
  dependencies:
    - build
  tags:
    - docker

