variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
# PREFIX: /usr/
  DOCKER_FILE: utils/Dockerfile
  DOCKER_TAG: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: cricket
  # MAKE_OPTS: -j 16

before_script:
  - git config --local core.longpaths true
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - prepare
  - build
  - test

# For some reason, GitLab CI prunes the contents of the submodules so we need to restore them.
before_script:
#   - git submodule foreach git checkout .

# Stage: prepare
##############################################################################

# Build docker image
prepare:centos7:docker-dev:
  stage: prepare
  script:
    - mkdir .ssh
    - cp -r ~/.ssh .ssh
    - docker build
        --file ${DOCKER_FILE}
        --tag ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
        --tag ${DOCKER_IMAGE_DEV}:latest .
  tags:
    - shell
    - linux

# check if styleguide is fulfilled
#style_check:
#  stage: build
#  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
#  allow_failure: true
#  tags:
#    - docker
#  script:
#    - ls
#    - utils/test_style.sh

# Stage: build
##############################################################################

build:
  stage: build
  script:
   - make -j 32
  artifacts:
    expire_in: 1 week
    paths:
      - cpu/cricket-client.so
      - cpu/cricket-server.so
      - gpu/cricket
      - tests/test_kernel
      - submodules/libtirpc/install/lib/libtirpc.so*
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
  cache:
    paths:
      - gpu/build
      - cpu/*.o
      - tests/*.o
      - submodules/libtirpc/install
    key: build
  tags:
    - docker


test:
  stage: test
  variables:
    RDIR: '/tmp/gitlab-jobs/$CI_PROJECT_NAME/$CI_JOB_ID'
  script:
    - ssh gitlab-runner@ghost mkdir -p $RDIR
    - scp cpu/cricket-server.so gitlab-runner@ghost:$RDIR/
    - scp submodules/libtirpc/install/lib/libtirpc.so* gitlab-runner@ghost:$RDIR/
    - scp tests/test_kernel gitlab-runner@ghost:$RDIR/
    - ssh gitlab-runner@ghost "LD_PRELOAD=$RDIR/libtirpc.so.3:$RDIR/cricket-server.so $RDIR/test_kernel" &
    - sleep 5
    - LD_PRELOAD=$PWD/submodules/libtirpc/install/lib/libtirpc.so.3:$PWD/cpu/cricket-client.so tests/test_kernel
  after_script:
    - ssh gitlab-runner@ghost rm -rf $RDIR
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
  dependencies:
    - build
  tags:
    - docker

